"use strict";

let movies = [
	{
		image: "/img/1.jpg",
		id: 1,
		name: "The Lord of the Rings: The Fellowship of the Ring",
		year: 2001,
		age: 12,
		genre: "fantasy",
		rate: 5,
		vid:"/vid/TheLordOfTheRingsTrailer.mp4",
		poster:"/vid/RingPoster.jpg",
		additImages1:"/img/addit/1.1.jpg",
		additImages2:"/img/addit/1.2.webp",
		additImages3:"/img/addit/1.3.png",
	},
	{
		image: "/img/2.jpg",
		id: 2,
		name: "Kung Fu Panda",
		year: 2009,
		age: 6,
		genre: "action",
		rate: 4,
		vid:"/vid/pandaTrailer.mp4",
		poster:"/vid/pandaTrailerPoster.webp",
		additImages1:"/img/addit/2.1.jpg",
		additImages2:"/img/addit/2.2.jpg",
		additImages3:"/img/addit/2.3.jpg",
	},
	{
		image: "/img/3.jpg",
		id: 3,
		name: "The Matrix",
		year: 1999,
		age: 16,
		genre: "action",
		rate: 5,
		vid:"/vid/matrixTrailer.mp4",
		poster:"/vid/matrixPoster.jpg",
		additImages1:"/img/addit/3.1.jpg",
		additImages2:"/img/addit/3.2.webp",
		additImages3:"/img/addit/3.3.webp",
	},
	{
		image: "/img/4.jpg",
		id: 4,
		name: "Forrest Gump",
		year: 1994,
		age: 12,
		genre: "drama",
		rate: 4,
		vid:"/vid/ForrestGumpTrailer.mp4",
		poster:"/vid/ForestGumpPoster.jpg",
		additImages1:"/img/addit/4.1.webp",
		additImages2:"/img/addit/4.2.webp",
		additImages3:"/img/addit/4.3.jpg",
	},
	{
		image: "/img/5.jpg",
		id: 5,
		name: "Warrior Nun",
		year: 2020,
		age: 12,
		genre: "fantasy",
		rate: 3,
		vid:"/vid/WarriorNunTrailer.mp4",
		poster:"/vid/WarriorNunPoster.jpg",
		additImages1:"/img/addit/5.1.jpg",
		additImages2:"/img/addit/5.2.webp",
		additImages3:"/img/addit/5.3.jpg",
	},
	{
		image: "/img/6.webp",
        id: 6,
        name: "Up",
        year: 2009,
        age: 0,
        genre: "adventure",
        rate: 5,
		vid:"/vid/UpTrailer.mp4",
		poster:"/vid/UpPoster.webp",
		additImages1:"/img/addit/6.1.jpg",
		additImages2:"/img/addit/6.2.jpg",
		additImages3:"/img/addit/6.3.webp",
    },
	{
		image: "/img/7.jpg",
        id: 7,
        name: "Inception",
        year: 2010,
        age: 12,
        genre: "action",
        rate: 5,
		vid:"/vid/InceptionTrailer.mp4",
		poster:"/vid/InceptionPoster.jpg",
		additImages1:"/img/addit/7.1.jpg",
		additImages2:"/img/addit/7.2.avif",
		additImages3:"/img/addit/7.3.jpg",
    },
	{
		image: "/img/8.jpg",
        id: 8,
        name: "Parasite",
        year: 2019,
        age: 18,
        genre: "thriller",
        rate: 4,
		vid:"/vid/GisaengchungTrailer.mp4",
		poster:"/vid/GisaengchungPoster.jpg",
		additImages1:"/img/addit/8.1.jpg",
		additImages2:"/img/addit/8,2.jpg",
		additImages3:"/img/addit/8.3.jpg",
    },
	{
		image: "/img/9.jpg",
        id: 9,
        name: "The Northman",
        year: 2022,
        age: 12,
        genre: "action",
        rate: 5,
		vid:"/vid/THE NORTHMANTrailer.mp4",
		poster:"/vid/theNorthmanPoster.jpg",
		additImages1:"/img/addit/9.1.jpg",
		additImages2:"/img/addit/9.2.jpg",
		additImages3:"/img/addit/9.3.jpg",
    },
	{
		image: "/img/10.webp",
        id: 10,
        name: "Sherlock",
        year: 2011,
        age: 16,
        genre: "drama",
        rate: 4,
		vid:"/vid/SherlockTrailer.mp4",
		poster:"/vid/SherlockPoster.jpg",
		additImages1:"/img/addit/10.1.jpg",
		additImages2:"/img/addit/10.2.jpg",
		additImages3:"/img/addit/10.3.jpg",
    },
];
